### ISSUE TITLE
Deployment with docker-compose

### ISSUE THREAD

**Issue by nlamirault** [nlamirault/home-assistant-configuration#1]
The docker-compose.yml file : 

```yaml
version: '2'

services:

#  db:
#    image: hypriot/rpi-mysql:5.5
#    volumes:
#        - /srv/docker/mysql:/var/lib/mysql
#     ports:
#       - "3306:3306"
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: 'Root_PW'
#       MYSQL_DATABASE: 'homeassistant'
#       MYSQL_USER: 'hass'
#       MYSQL_PASSWORD: 'MYSQL_PASSWORD'

  homeassistant:
#    depends_on:
#      - db
    image: homeassistant/raspberrypi3-homeassistant:0.49.1
    container_name: homeassistant
    ports:
      - "8123:8123"
    volumes:
      - /home/pirate/Projets/home-assistant-configuration:/config
    network_mode: host
    restart: always
```
