### ISSUE TITLE
Kubernetes deployment

### ISSUE THREAD

**Issue by nlamirault** [nlamirault/home-assistant-configuration#2]
Generate configuration to deploy home assistant to a Kubernetes cluster.

**Comment by nlamirault** [comment]
Try with : 

* namespace.yaml : 

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: homeassistant
```

* service.yaml file : 

```yaml
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: homeassistant
  labels:
    app: homeassistant
spec:
  ports:
  - port: 8123
    # name: ui
    # targetPort: ui
  selector:
    app: homeassistant
```

* deployment.yaml : 

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: homeassistant
  namespace: homeassistant
  labels:
    app: homeassistant
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
      - image: homeassistant/raspberrypi3-homeassistant:0.51.1
        name: homeassistant
        ports:
        - containerPort: 8123
        volumeMounts:
        - name: config
          mountPath: /etc/homeassistant
      volumes:
      - name: config
        configMap:
          name: homeassistant
      - name: data
        hostPath:
        path: /srv/home-assistant-data
      hostNetwork: true
```

* ingress.yaml : 

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: homeassistant
  namespace: homeassistant
  labels:
    app: homeassistant
  annotations:
    # ingress.kubernetes.io/auth-secret: discourse-basic-auth
    # ingress.kubernetes.io/auth-type: basic
    # ingress.kubernetes.io/auth-realm: "thisone"
    # kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: homeassistant.things.local
    http:
      paths:
      - backend:
          serviceName: homeassistant
          servicePort: 8123
        path: /
```
